### ISSUE TITLE
Write up documentation for the project and application.

### ISSUE THREAD

**Issue by DAghaSolent** [GDoesCode/COM619DevOpsGroupWork#18]

**Comment by GDoesCode** [comment]
- your architecture and design decisions
This is Ahub's decision to go with Node.js and JavaScript since he had a working application but just needed it to be tweaked for client requirements. You have your architecture when it comes to cloud and hosting on azure.
Testing is utilising Selenium IDE to automate our tests.
- your project plan and work allocation to the team
       Both the GitHub boards with the tasks and the requirements.
Josh - deployment 
Jacob - Maintenance and Testing(Secondary)
Gaetano - Testing and Maintenance(Secondary)
Ahub - Development 
Danny - Project management, support and general doing the shit jobs.
- Progress against your project plan
     Talk about how were nearly finishing up on development and moving into testing, maintenance, documentation and video.

- any demos of implementation
      Probably not but no harm in showcasing it.
next steps
      Finishing Development to move into Testing, Maintenance, Documentation and Video
